# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='shelf_life',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
